name: Build and Publish PDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install LaTeX
#        run: sudo apt-get update && sudo apt-get install -y texlive-full pandoc

#      - name: Build PDF
#        run: make

#      - name: Upload PDF artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: system-pdfs
#          path: | 
#            systemnotes.pdf
#            openinglist.pdf
#            prepareddefences.pdf

#      - name: Convert README.md to index.html
#        run: |
#          pandoc README.md -o index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            README.md
            level4.pdf
            level5.pdf

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

